name: Publish draft release

on:
  push:
    branches:
      - lemarier-update-build
    tags:
      # Catches v1.2.3 and v1.2.3-rc1
      - v[0-9]+.[0-9]+.[0-9]+*

jobs:
  build:
    name: ${{ matrix.kind }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build library
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: |
            target/release/*.dll
            target/release/*.dylib
            target/release/*.so

      # generate bindgen from `bindings.json`
      - name: Generate bindgen and documentation
        if: matrix.os == 'ubuntu-latest'
        run: |
          curl -fsSL https://get.mashin.land | sh
          export PATH="/home/runner/.mashin/bin:$PATH"
          mashin bindgen ./bindings.json
          mashin doc ./mod.ts

      # generate doc from the `mod.ts` generated previously
      - name: Upload bindgen and documentation
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v3
        with:
          name: bindgen-doc
          path: |
            mod.ts
            mod.json

      - name: Draft release
        uses: softprops/action-gh-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          draft: true
          files: |
            target/release/*.dll
            target/release/*.dylib
            target/release/*.so